### ISSUE TITLE
ERROR: bad md5sum for file /tmp/pear/temp/PDO_IBM/package.xml

### ISSUE THREAD

**Issue by tessus** [php/pecl-database-pdo_ibm#25]
Something seems off with the pecl package:

```
# pecl install PDO_IBM
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
downloading PDO_IBM-1.6.0.tgz ...
Starting to download PDO_IBM-1.6.0.tgz (99,480 bytes)
......................done: 99,480 bytes
ERROR: bad md5sum for file /tmp/pear/temp/PDO_IBM/package.xml
```

**Comment by NattyNarwhal** [comment]
I can reproduce this - I think the problem is that the PDO_IBM package.xml lists itself. When you do `pecl package`, it writes checksums into the package.xml inside of the package, but the package.xml file would be changed from this, making the checksum it wrote for itself invalid. From the extracted PECL package:

```
calvin@anika PDO_IBM-1.6.0 % grep package.xml package.xml 
   <file baseinstalldir="pdo_ibm" md5sum="83626e44ce83dd4295807a0ee9a3c9b2" name="package.xml" role="src" />
calvin@anika PDO_IBM-1.6.0 % md5 package.xml 
MD5 (package.xml) = 740cdec698051aa1cdab3ec6cb9a9b06
```

And from the repo:

```
calvin@anika pecl-database-pdo_ibm % md5 package.xml 
MD5 (package.xml) = 83626e44ce83dd4295807a0ee9a3c9b2
```

I'm wondering why this hasn't caused problems earlier though.

**Comment by tessus** [comment]
hmm, e.g. the ibm_db2 doesn't throw any errors, nor did the previous PDO package. So yea, kind of interesting why this is showing up now.
Who is creating the packages? Are the done mnually or via a pipeline?

**Comment by NattyNarwhal** [comment]
I'm suspecting maybe a PEAR change, but I don't think they would have special-cased package.xml?

I'm running `pecl package` on packages manually and getting @theprez to push to PECL since he has write permissions to PECL for the packages and we don't. I let CI pass on a commit before I package it, and that does include some additional validations that `pecl package-validate` doesn't do, but PECL does.

I wouldn't mind moving more of the packaging steps to CI (tag to PECL push) and adding further checks to the packaging though. For now I'll fix the package.xml and push a new release.
